# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 03:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(help_text='Message contents.', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time when message was created.')),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counsellor_instance', models.ForeignKey(help_text='Counsellor instance.', on_delete=django.db.models.deletion.CASCADE, to='users.CounsellorUser')),
                ('user_instance', models.ForeignKey(help_text='Spark user instance.', on_delete=django.db.models.deletion.CASCADE, to='users.SparkUser')),
            ],
        ),
        migrations.CreateModel(
            name='LastConvoMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Full name of the sender', max_length=200)),
                ('message', models.CharField(help_text='Last message sent in this conversation.', max_length=1000)),
                ('created_at', models.DateTimeField(help_text='Time when the message was added to the system.')),
                ('relation', models.OneToOneField(help_text='Last message sent in this conversation.', on_delete=django.db.models.deletion.CASCADE, to='chat.Conversation')),
            ],
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='relation',
            field=models.ForeignKey(help_text='Conversation that the message belongs to.', on_delete=django.db.models.deletion.CASCADE, to='chat.Conversation'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(help_text='Sender of the message.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together=set([('counsellor_instance', 'user_instance')]),
        ),
    ]
