# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-09 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastConvoMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Full name of the sender', max_length=200)),
                ('message', models.CharField(help_text='Last message sent in this conversation.', max_length=1000)),
                ('relation', models.OneToOneField(help_text='Last message sent in this conversation.', on_delete=django.db.models.deletion.CASCADE, to='chat.Conversation')),
            ],
        ),
    ]
