# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-09 10:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_lastconvomessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastconvomessage',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 9, 10, 52, 21, 908949, tzinfo=utc), help_text='Time when the message was added to the system.'),
        ),
    ]
