# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20160114_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastconvomessage',
            name='last_name',
            field=models.CharField(help_text='Last Name of the sender', max_length=200),
        ),
    ]
