# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-09 10:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_lastconvomessage_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastconvomessage',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 9, 10, 56, 43, 152611, tzinfo=utc), help_text='Time when the message was added to the system.'),
        ),
    ]
