# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-09 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20160109_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastconvomessage',
            name='created_at',
            field=models.DateTimeField(help_text='Time when the message was added to the system.'),
        ),
    ]
