# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-09 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparkuser',
            name='bio',
            field=models.CharField(blank=True, help_text='Optional description about this user.', max_length=200, null=True),
        ),
    ]
