# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-08 14:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the forum.', max_length=50)),
                ('description', models.CharField(help_text='Description of the forum.', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The Date & Time when this forum was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time forum details were updated.')),
            ],
        ),
        migrations.CreateModel(
            name='ForumMemeber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forum_relation', models.ForeignKey(help_text='Forum which user is a memebr.', on_delete=django.db.models.deletion.CASCADE, to='forums.Forum')),
                ('user_relation', models.ForeignKey(help_text='User who has joined a forum.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ForumMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date of Time of message posting.')),
                ('message', models.CharField(help_text='Mesasge content.', max_length=1000)),
                ('relation', models.ForeignKey(help_text='Forum that message belongs to.', on_delete=django.db.models.deletion.CASCADE, to='forums.Forum')),
                ('sender', models.ForeignKey(help_text='Sender of the message', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='forummemeber',
            unique_together=set([('forum_relation', 'user_relation')]),
        ),
    ]
