# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-08 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ForumMemeber',
            new_name='ForumMember',
        ),
    ]
