# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 01:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('forums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(help_text='Message content.', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time of forum request submission.')),
                ('relation', models.ForeignKey(help_text='Spark user requesting a new forum.', on_delete=django.db.models.deletion.CASCADE, to='users.SparkUser')),
            ],
        ),
    ]
