# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 02:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('forums', '0002_forumrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(help_text='Message of reporter.', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the forum was reported.')),
                ('forum_relation', models.ForeignKey(help_text='Forum being reported.', on_delete=django.db.models.deletion.CASCADE, to='forums.Forum')),
                ('relation', models.ForeignKey(help_text='Spark user who is reporting a forum.', on_delete=django.db.models.deletion.CASCADE, to='users.SparkUser')),
            ],
        ),
        migrations.CreateModel(
            name='LastForumMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='First name of last message sender.', max_length=200)),
                ('last_name', models.CharField(help_text='Last name of last message sender.', max_length=200)),
                ('mesasge', models.CharField(help_text='Last message sent in forum.', max_length=1000)),
                ('created_at', models.DateTimeField(help_text='Time when last message was sent in forum.')),
                ('relation', models.OneToOneField(help_text='Last/latest message sent in forum.', on_delete=django.db.models.deletion.CASCADE, to='forums.Forum')),
            ],
        ),
        migrations.AddField(
            model_name='forumrequest',
            name='forum_name',
            field=models.CharField(default='N/a', help_text='Proposed forum name.', max_length=50),
        ),
    ]
