# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0003_auto_20160113_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumrequest',
            name='forum_name',
            field=models.CharField(help_text='Proposed forum name.', max_length=50),
        ),
    ]
